export const GET_PROJECTS_REQUEST = '@projects/GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = '@projects/GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = '@projects/GET_PROJECTS_FAILURE';

export const GET_PROJECT_REQUEST = '@projects/GET_PROJECT_REQUEST';
export const GET_PROJECT_SUCCESS = '@projects/GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILURE = '@projects/GET_PROJECT_FAILURE';

export const SET_PROJECT = '@projects/SET_PROJECT';
export const SET_PROJECTS = '@projects/SET_PROJECTS';


export const GET_CONTRIBUTIONS_REQUEST = '@contributions/GET_CONTRIBUTIONS_REQUEST';
export const GET_CONTRIBUTIONS_SUCCESS = '@contributions/GET_CONTRIBUTIONS_SUCCESS';
export const GET_CONTRIBUTIONS_FAILURE = '@contributions/GET_CONTRIBUTIONS_FAILURE';

export const GET_CONTRIBUTION_REQUEST = '@contributions/GET_CONTRIBUTION_REQUEST';
export const GET_CONTRIBUTION_SUCCESS = '@contributions/GET_CONTRIBUTION_SUCCESS';
export const GET_CONTRIBUTION_FAILURE = '@contributions/GET_CONTRIBUTION_FAILURE';

export const CREATE_CONTRIBUTION_REQUEST = '@contributions/CREATE_CONTRIBUTION_REQUEST';
export const CREATE_CONTRIBUTION_SUCCESS = '@contributions/CREATE_CONTRIBUTION_SUCCESS';
export const CREATE_CONTRIBUTION_FAILURE = '@contributions/CREATE_CONTRIBUTION_FAILURE';

export const UPDATE_CONTRIBUTION_REQUEST = '@contributions/UPDATE_CONTRIBUTION_REQUEST';
export const UPDATE_CONTRIBUTION_SUCCESS = '@contributions/UPDATE_CONTRIBUTION_SUCCESS';
export const UPDATE_CONTRIBUTION_FAILURE = '@contributions/UPDATE_CONTRIBUTION_FAILURE';

export const SET_CONTRIBUTION = '@contributions/SET_CONTRIBUTION';
export const SET_CONTRIBUTIONS = '@contributions/SET_CONTRIBUTIONS';

