export const GET_PROJECTS_REQUEST = '@projects/GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = '@projects/GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = '@projects/GET_PROJECTS_FAILURE';

export const CURRENT_SCOPE_VERSION = 5;
export const REQUIRED_SCOPE_VERSION = 5; // at least

/* SCOPE VERSIONS
1: original
2: added organizations
3,4: attempted fixed organizations bugs
5: fully fixed organization bugs
*/

export const GET_PROJECT_REQUEST = '@project/GET_PROJECT_REQUEST';
export const GET_PROJECT_SUCCESS = '@project/GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILURE = '@project/GET_PROJECT_FAILURE';

export const BAN_USER_REQUEST = '@user/BAN_USER_REQUEST';
export const BAN_USER_SUCCESS = '@user/BAN_USER_SUCCESS';
export const BAN_USER_FAILURE = '@user/BAN_USER_FAILURE';

export const SET_PROJECT = '@project/SET_PROJECT';
export const SET_PROJECTS = '@project/SET_PROJECTS';

export const GET_CONTRIBUTIONS_REQUEST = '@contributions/GET_CONTRIBUTIONS_REQUEST';
export const GET_CONTRIBUTIONS_SUCCESS = '@contributions/GET_CONTRIBUTIONS_SUCCESS';
export const GET_CONTRIBUTIONS_FAILURE = '@contributions/GET_CONTRIBUTIONS_FAILURE';

export const SET_CONTRIBUTION = '@contribution/SET_CONTRIBUTION';

export const GET_CONTRIBUTION_REQUEST = '@contribution/GET_CONTRIBUTION_REQUEST';
export const GET_CONTRIBUTION_SUCCESS = '@contribution/GET_CONTRIBUTION_SUCCESS';
export const GET_CONTRIBUTION_FAILURE = '@contribution/GET_CONTRIBUTION_FAILURE';

export const SET_CONTRIBUTION_HVS_REQUEST = '@contribution/SET_CONTRIBUTION_HVS_REQUEST';
export const SET_CONTRIBUTION_HVS_SUCCESS = '@contribution/SET_CONTRIBUTION_HVS_SUCCESS';
export const SET_CONTRIBUTION_HVS_FAILURE = '@contribution/SET_CONTRIBUTION_HVS_FAILURE';

export const CREATE_CONTRIBUTION_REQUEST = '@contribution/CREATE_CONTRIBUTION_REQUEST';
export const CREATE_CONTRIBUTION_SUCCESS = '@contribution/CREATE_CONTRIBUTION_SUCCESS';
export const CREATE_CONTRIBUTION_FAILURE = '@contribution/CREATE_CONTRIBUTION_FAILURE';

export const UPDATE_CONTRIBUTION_REQUEST = '@contribution/UPDATE_CONTRIBUTION_REQUEST';
export const UPDATE_CONTRIBUTION_SUCCESS = '@contribution/UPDATE_CONTRIBUTION_SUCCESS';
export const UPDATE_CONTRIBUTION_FAILURE = '@contribution/UPDATE_CONTRIBUTION_FAILURE';

export const MODERATOR_ACTION_REQUEST = '@contribution/MODERATOR_ACTION_REQUEST';
export const MODERATOR_ACTION_SUCCESS = '@contribution/MODERATOR_ACTION_SUCCESS';
export const MODERATOR_ACTION_FAILURE = '@contribution/MODERATOR_ACTION_FAILURE';

export const SET_CONTRIBUTIONS = '@contribution/SET_CONTRIBUTIONS';

export const CREATE_SPONSOR_REQUEST = '@sponsor/CREATE_SPONSOR_REQUEST';
export const CREATE_SPONSOR_SUCCESS = '@sponsor/CREATE_SPONSOR_SUCCESS';
export const CREATE_SPONSOR_FAILURE = '@sponsor/CREATE_SPONSOR_FAILURE';

export const GET_SPONSORS_REQUEST = '@sponsors/GET_SPONSORS_REQUEST';
export const GET_SPONSORS_SUCCESS = '@sponsors/GET_SPONSORS_SUCCESS';
export const GET_SPONSORS_FAILURE = '@sponsors/GET_SPONSORS_FAILURE';

export const GET_MODERATORS_REQUEST = '@sponsors/GET_MODERATORS_REQUEST';
export const GET_MODERATORS_SUCCESS = '@sponsors/GET_MODERATORS_SUCCESS';
export const GET_MODERATORS_FAILURE = '@sponsors/GET_MODERATORS_FAILURE';

export const GET_STATS_REQUEST = '@stats/GET_STATS_REQUEST';
export const GET_STATS_SUCCESS = '@stats/GET_STATS_SUCCESS';
export const GET_STATS_FAILURE = '@stats/GET_STATS_FAILURE';

export const GET_SPONSORS_BENEFICIARIES_REQUEST = '@sponsors/GET_SPONSORS_BENEFICIARIES_REQUEST';
export const GET_SPONSORS_BENEFICIARIES_SUCCESS = '@sponsors/GET_SPONSORS_BENEFICIARIES_SUCCESS';
export const GET_SPONSORS_BENEFICIARIES_FAILURE = '@sponsors/GET_SPONSORS_BENEFICIARIES_FAILURE';

export const GET_BENEFICIARIES_REQUEST = '@beneficiaries/GET_BENEFICIARIES_REQUEST';
export const GET_BENEFICIARIES_SUCCESS = '@beneficiaries/GET_BENEFICIARIES_SUCCESS';
export const GET_BENEFICIARIES_FAILURE = '@beneficiaries/GET_BENEFICIARIES_FAILURE';

export const CREATE_GITHUB_USER_REQUEST = '@user/CREATE_GITHUB_USER_REQUEST';
export const CREATE_GITHUB_USER_SUCCESS = '@user/CREATE_GITHUB_USER_SUCCESS';
export const CREATE_GITHUB_USER_FAILURE = '@user/CREATE_GITHUB_USER_FAILURE';

export const GET_GITHUB_PROJECTS_REQUEST = '@user/GET_GITHUB_PROJECTS_REQUEST';
export const GET_GITHUB_PROJECTS_SUCCESS = '@user/GET_GITHUB_PROJECTS_SUCCESS';
export const GET_GITHUB_PROJECTS_FAILURE = '@user/GET_GITHUB_PROJECTS_FAILURE';

export const GET_GITHUB_ORG_PROJECTS_REQUEST = '@user/GET_GITHUB_ORG_PROJECTS_REQUEST';
export const GET_GITHUB_ORG_PROJECTS_SUCCESS = '@user/GET_GITHUB_ORG_PROJECTS_SUCCESS';
export const GET_GITHUB_ORG_PROJECTS_FAILURE = '@user/GET_GITHUB_ORG_PROJECTS_FAILURE';

export const GET_GITHUB_ORG_PROJECTS_REQUEST_INTERNAL = '@user/GET_GITHUB_ORG_PROJECTS_REQUEST_INTERNAL';
export const GET_GITHUB_ORG_PROJECTS_SUCCESS_INTERNAL = '@user/GET_GITHUB_ORG_PROJECTS_SUCCESS_INTERNAL';
export const GET_GITHUB_ORG_PROJECTS_FAILURE_INTERNAL = '@user/GET_GITHUB_ORG_PROJECTS_FAILURE_INTERNAL';

export const GET_USER_REQUEST = '@user/GET_USER_REQUEST';
export const GET_USER_SUCCESS = '@user/GET_USER_SUCCESS';
export const GET_USER_FAILURE = '@user/GET_USER_FAILURE';

export const GET_GITHUB_PR_REQUEST = '@pullRequests/GET_GITHUB_PR_REQUEST';
export const GET_GITHUB_PR_SUCCESS = '@pullRequests/GET_GITHUB_PR_SUCCESS';
export const GET_GITHUB_PR_FAILURE = '@pullRequests/GET_GITHUB_PR_FAILURE';


